import pymysql
pymysql.install_as_MySQLdb()

# import base64
# print(base64.b64decode('MTkxYWUzZjU0Yjg1ZWY1NjNiMzA3M2I1NTY0MmZkNmExMDcwZjkxNzp7InFzIjp7ImlkIjoxLCJwYXNzd2QiOiI5NmU3OTIxODk2NWViNzJjOTJhNTQ5ZGQ1YTMzMDExMiIsInVzZXJuYW1lIjoiMTExMTExIiwicGhvdG8iOiJwaG90b3MvbXM4LmpwZyJ9fQ=='))