# Generated by Django 2.0.6 on 2018-07-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=32)),
                ('photo', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
